spring.application.name=application
spring.security.user.name=admin
spring.security.user.password=admin
#server.port=5000

spring.datasource.url=jdbc:mysql://localhost:3306/sso-master
spring.datasource.username=root
spring.datasource.password=root

## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update
logging.level.org.hibernate = ERROR
spring.main.allow-bean-definition-overriding=true
spring.main.allow-circular-references=true
jwt.secret=linh
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.mvc.converters.preferred-json-mapper=jackson


spring.profiles.active=dev
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=duylinh19981007@gmail.com
spring.mail.password=njnu jpcn kzsu tbmk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
